from webportal.client_api.ondemand.conftest import *
from webportal.client_api.what_to_watch.conftest import *
from webportal.client_api.search.conftest import *


@pytest.mark.usefixtures("setup_ondemand")
@pytest.mark.usefixtures("setup_what_to_watch")
@pytest.mark.usefixtures("setup_search")
@pytest.mark.skipif("retail" in Settings.mso.lower(), reason="No On Demand for Retail")
class TestOnDemand:

    @pytest.mark.sanity
    def test_14391544_Buy_Confirmation_Pop(self):
        """https://testrail.tivo.com/index.php?/cases/view/14391544 """
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TVOD submenu")
        self.ondemand_page.go_to_Movies_folder()
        self.log.step("Click on All titles")
        self.ondemand_page.click_on_All_Titles()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Rent a movie")
        (movie, text) = self.ondemand_page.select_TVOD_Unencrypted_item()
        self.log.step("Check CONFIRM PURCHASE pop-up")
        self.ondemand_assertions.assert_pop_up(movie, text)
        self.log.step("Cancel CONFIRMATION PURCHASE pop-up")
        self.ondemand_page.cancel_pop_up()
        self.log.step("All pop-ups are closed")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Reopen CONFIRMATION PURCHASE pop-up for close")
        text = self.ondemand_page.open_pop_up()
        self.log.step("Close Confirmation Purchase pop-up")
        self.ondemand_page.close_pop_up()
        self.log.step("Verify pop-up closer after exit")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Confirmation purchase and open player")
        text = self.ondemand_page.open_pop_up()
        self.ondemand_page.confirm_purchase()
        self.log.step("Verify web player is present")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_19779778_tvod_watch_now_outside(self):
        """https://testrail.tivo.com/index.php?/cases/view/19779778"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TVOD submenu")
        self.ondemand_page.go_to_Movies_folder()
        self.log.step("Click on All titles")
        self.ondemand_page.click_on_All_Titles()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Rent a movie")
        (movie, text) = self.ondemand_page.select_TVOD_Unencrypted_item()
        self.log.step("Check CONFIRM PURCHASE pop-up")
        self.ondemand_assertions.assert_pop_up(movie, text)
        self.log.step("Cancel CONFIRMATION PURCHASE pop-up")
        self.ondemand_page.cancel_pop_up()
        self.log.step("All pop-ups are closed")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Click the Search option from the global navigation")
        self.search_page.text_search_field(movie)
        self.log.step("Verify the entered Item in the Displayed List")
        self.search_assertions.verify_search_list_results(movie)
        self.log.step("Click on First Movie from Search List")
        self.ondemand_page.click_movie()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Watch now pop-up opens")
        self.ondemand_assertions.assert_TVOD_offer_in_Watch_Now()
        self.log.step("Click watch now option")
        self.ondemand_page.click_pop_up_watch_now()
        self.log.step("Check CONFIRM PURCHASE pop-up")
        self.ondemand_assertions.assert_pop_up(movie, text)
        self.log.step("Click on Confirm purchase")
        self.ondemand_page.confirm_purchase()
        self.log.step("Verify web player is present")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_19779229_tvod_resume_play(self):
        """https://testrail.tivo.com/index.php?/cases/view/19779229"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Find rated TVOD")
        self.ondemand_page.select_TVOD_Encrypted_item()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Verify WN pop-up or player is present")
        self.ondemand_assertions.assert_TVOD_offer_displayed()
        self.log.step("Play streaming")
        self.ondemand_page.web_player_playing_or_wn()
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Close web player")
        self.ondemand_page.close_web_player()
        self.log.step("Verify no web player is present")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Open resume option")
        self.ondemand_page.click_watch_now_btn()
        self.ondemand_page.resume()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_19779230_tvod_start_over_play(self):
        """https://testrail.tivo.com/index.php?/cases/view/19779230"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Find rated TVOD")
        self.ondemand_page.select_TVOD_Encrypted_item()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Verify WN pop-up or player is present")
        self.ondemand_assertions.assert_TVOD_offer_displayed()
        self.log.step("Play streaming")
        self.ondemand_page.web_player_playing_or_wn()
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Close web player")
        self.ondemand_page.close_web_player()
        self.log.step("Verify no web player is present")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Open start over option")
        self.ondemand_page.click_watch_now_btn()
        self.ondemand_page.start_over()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_11123251_play_preview_ondemand(self):
        """https://testrail.tivo.com/index.php?/cases/view/11123251"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TVOD submenu")
        self.ondemand_page.go_to_Movies_folder()
        self.log.step("Click on All titles")
        self.ondemand_page.click_on_All_Titles()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Select movie")
        self.ondemand_page.select_first_movie()
        self.log.step("Preview button exists")
        self.ondemand_assertions.assert_preview_btn_present()
        self.log.step("Click on Preview button")
        self.ondemand_page.click_preview_btn()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_11123248_ipvod_resume_play(self):
        """https://testrail.tivo.com/index.php?/cases/view/11123248"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TiVo submenu")
        self.ondemand_page.go_to_TiVo_submenu()
        self.log.step("Click on Rating folder")
        self.ondemand_page.click_on_Rating_folder()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Find IPVOD content")
        self.ondemand_page.select_IPVOD_item()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Verify WN pop-up or player is present")
        self.ondemand_assertions.assert_TVOD_offer_displayed()
        self.log.step("Play streaming")
        self.ondemand_page.web_player_playing_or_wn()
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Close web player")
        self.ondemand_page.close_web_player()
        self.log.step("Verify no web player is present")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Open resume option")
        self.ondemand_page.click_watch_now_btn()
        self.ondemand_page.resume()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_11123252_ipvod_start_over_play(self):
        """https://testrail.tivo.com/index.php?/cases/view/11123252"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TiVo submenu")
        self.ondemand_page.go_to_TiVo_submenu()
        self.log.step("Click on Rating folder")
        self.ondemand_page.click_on_Rating_folder()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Find IPVOD content")
        self.ondemand_page.select_IPVOD_item()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Verify WN pop-up or player is present")
        self.ondemand_assertions.assert_TVOD_offer_displayed()
        self.log.step("Play streaming")
        self.ondemand_page.web_player_playing_or_wn()
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Close web player")
        self.ondemand_page.close_web_player()
        self.log.step("Verify no web player is present")
        self.ondemand_assertions.assert_pop_up_not_present()
        self.log.step("Open start over option")
        self.ondemand_page.click_watch_now_btn()
        self.ondemand_page.start_over()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()

    @pytest.mark.sanity
    def test_19783861_ipvod_play(self):
        """https://testrail.tivo.com/index.php?/cases/view/19783861"""
        self.log.step("Login to current account")
        self.wtw_page.select_button_sign_in()
        self.wtw_page.log_in()
        self.wtw_assertions.mainPageTabs_assert()
        self.log.step("Go To 'On Demand - My Rentals'")
        self.ondemand_page.go_to_OnDemand()
        self.log.step("Verify MyRentals page is present")
        self.ondemand_assertions.assert_on_demand_menu()
        self.log.step("Click on TiVo submenu")
        self.ondemand_page.go_to_TiVo_submenu()
        self.log.step("Click on Rating folder")
        self.ondemand_page.click_on_Rating_folder()
        self.log.step("Check all titles assets")
        self.ondemand_assertions.assert_all_titles()
        self.log.step("Find IPVOD content")
        self.ondemand_page.select_IPVOD_item()
        self.log.step("Click on Watch now button")
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Verify WN pop-up or player is present")
        self.ondemand_assertions.assert_TVOD_offer_displayed()
        self.log.step("Play streaming")
        self.ondemand_page.web_player_playing_or_wn()
        self.ondemand_page.click_watch_now_btn()
        self.log.step("Web player is opening")
        self.ondemand_assertions.assert_player_present()
